# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 931ccd1c63cd05afc009de29aa82e2ac491e3e1c6863b47fddf1be42e501e3b0917f28dc480abaf6e4ce1b76cdc70e6d2f60d5790ee2abd42dd17ece2f0fe68c

test:
  secret_key_base: 2f62229dfe69698a7527e827eef7cdceaeeaf2430fd594ad43308b384d38a4000a02d5d6af3edd0bc1e625a3cc5702a34c953463c971b789b8b4b8183a6f11af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
